# File: ./docstra/core/documentation/setup.py

import argparse
import os
import subprocess
import sys
from pathlib import Path
from typing import List


def check_dependencies() -> List[str]:
    """Check if required dependencies are installed."""
    dependencies = ["mkdocs", "mkdocs-material", "pymdown-extensions", "mkdocstrings"]
    missing: List[str] = []

    for dep in dependencies:
        try:
            # Try to import the package
            if dep == "mkdocs":
                subprocess.run(["mkdocs", "--version"], check=True, capture_output=True)
            elif dep == "mkdocs-material":
                import importlib

                importlib.import_module("material")
            elif dep == "pymdown-extensions":
                import importlib

                importlib.import_module("pymdownx")
            elif dep == "mkdocstrings":
                import importlib

                importlib.import_module("mkdocstrings")
        except (ImportError, subprocess.CalledProcessError, ModuleNotFoundError):
            missing.append(dep)

    return missing


def install_dependencies(missing_deps: List[str]) -> bool:
    """Install missing dependencies."""
    if not missing_deps:
        return True

    print(f"Installing missing dependencies: {', '.join(missing_deps)}")

    try:
        # Install missing dependencies using pip
        subprocess.run(
            [sys.executable, "-m", "pip", "install"] + missing_deps, check=True
        )
        return True
    except subprocess.CalledProcessError as e:
        print(f"Error installing dependencies: {e}")
        return False


def setup_mkdocs_environment(output_dir: str) -> bool:
    """Set up a basic MkDocs environment in the output directory."""
    output_path = Path(output_dir)

    # Create necessary directories
    docs_dir = output_path
    os.makedirs(docs_dir, exist_ok=True)

    # Create a basic index.md file if it doesn't exist
    index_path = docs_dir / "index.md"
    if not index_path.exists():
        with open(index_path, "w") as f:
            f.write(
                """# Documentation

This documentation site is generated by Docstra.

## Getting Started

Navigate through the documentation using the menu on the left.
"""
            )

    # Create a basic mkdocs.yml file if it doesn't exist
    config_path = output_path / "mkdocs.yml"
    if not config_path.exists():
        with open(config_path, "w") as f:
            f.write(
                """site_name: Project Documentation
theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - search.highlight
    - search.share
    - toc.follow
    - content.code.copy
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.critic
  - pymdownx.tasklist
  - admonition
  - toc
  - tables
plugins:
  - search
  - mkdocstrings
nav:
  - Home: index.md
"""
            )

    return True


def main() -> int:
    """Main entry point for the documentation setup script."""
    parser = argparse.ArgumentParser(
        description="Set up documentation environment for Docstra"
    )
    parser.add_argument(
        "--output", "-o", default="./docs", help="Output directory for documentation"
    )
    parser.add_argument(
        "--check-only",
        action="store_true",
        help="Only check dependencies without installing",
    )
    parser.add_argument(
        "--init", action="store_true", help="Initialize a basic MkDocs environment"
    )

    args = parser.parse_args()

    # Check dependencies
    missing_deps = check_dependencies()

    if missing_deps:
        print(f"Missing dependencies: {', '.join(missing_deps)}")

        if args.check_only:
            print("\nTo install, run:")
            print("  uv sync")
            return 1

        # Install dependencies
        if not install_dependencies(missing_deps):
            print("Failed to install dependencies. Please install them manually.")
            return 1
    else:
        print("All dependencies are already installed.")

    # Set up MkDocs environment if requested
    if args.init:
        if setup_mkdocs_environment(args.output):
            print(f"MkDocs environment initialized in {args.output}")
        else:
            print(f"Failed to initialize MkDocs environment in {args.output}")
            return 1

    print("\nSetup complete!")
    print(f"To serve documentation: cd {args.output} && mkdocs serve")

    return 0


if __name__ == "__main__":
    sys.exit(main())
